// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvayrpjykkkipwewwlka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2YXlycGp5a2traXB3ZXd3bGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzk1NzcsImV4cCI6MjA2ODg1NTU3N30.hA3UNGixHsrrcAx_VEmpuk6YzfXkrje9cWbTYVZKJKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});